
DROP TABLE IF EXISTS USUARIO;

CREATE TABLE USUARIO(
id_usuario INT PRIMARY KEY AUTO_INCREMENT,
nombre VARCHAR(40) UNIQUE NOT NULL,
password VARCHAR(50) NOT NULL,
email VARCHAR(80) UNIQUE NOT NULL,
tipo_usuario VARCHAR(20) CHECK(tipo_usuario IN ('administrador','estandar')) NOT NULL
);

DROP TABLE IF EXISTS LIBRO;

CREATE TABLE LIBRO(
id_libro INT PRIMARY KEY AUTO_INCREMENT,
titulo VARCHAR(40) NOT NULL,
autor VARCHAR(40) NOT NULL,
stock INT
);

DROP TABLE IF EXISTS INCIDENCIA;

CREATE TABLE INCIDENCIA(
id_incidencia INT PRIMARY KEY AUTO_INCREMENT,
usuario INT NOT NULL,
descripcion TEXT(200) NOT NULL,
fecha_incidencia datetime NOT NULL,
resuelta boolean NOT NULL,
CONSTRAINT fk_usuario FOREIGN KEY (usuario) REFERENCES USUARIO(id_usuario)  ON UPDATE CASCADE
);

DROP TABLE IF EXISTS PRESTAMO;

CREATE TABLE PRESTAMO(
id_prestamo INT PRIMARY KEY AUTO_INCREMENT,
usuario INT NOT NULL,
libro INT NOT NULL,
fecha_prestamo DATETIME NOT NULL,
fecha_devolucion DATETIME NOT NULL,
CONSTRAINT fk_usuario FOREIGN KEY (usuario) REFERENCES USUARIO(id_usuario)  ON UPDATE CASCADE,
CONSTRAINT fk_libro FOREIGN KEY (libro) REFERENCES LIBRO(id_libro) ON DELETE CASCADE ON UPDATE CASCADE
);
