-- MySQL Script generated by MySQL Workbench
-- Mon Jan 22 16:59:35 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema biblioteca
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `biblioteca` ;

-- -----------------------------------------------------
-- Schema biblioteca
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `biblioteca` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `biblioteca` ;

-- -----------------------------------------------------
-- Table `biblioteca`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `biblioteca`.`usuario` ;

CREATE TABLE IF NOT EXISTS `biblioteca`.`usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(40) NOT NULL,
  `password` VARCHAR(50) NOT NULL,
  `email` VARCHAR(80) NOT NULL,
  `tipo_usuario` VARCHAR(20) NOT NULL,
  `bloqueado` TINYINT NULL DEFAULT '0',
  `prestamo_activo` TINYINT(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `nombre` (`nombre` ASC) VISIBLE,
  UNIQUE INDEX `email` (`email` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `biblioteca`.`incidencia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `biblioteca`.`incidencia` ;

CREATE TABLE IF NOT EXISTS `biblioteca`.`incidencia` (
  `id_incidencia` INT NOT NULL AUTO_INCREMENT,
  `usuario` INT NOT NULL,
  `descripcion` TEXT NOT NULL,
  `fecha_incidencia` DATETIME NOT NULL,
  `resuelta` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id_incidencia`),
  INDEX `fk_usuario` (`usuario` ASC) VISIBLE,
  CONSTRAINT `fk_usuario`
    FOREIGN KEY (`usuario`)
    REFERENCES `biblioteca`.`usuario` (`id_usuario`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `biblioteca`.`libro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `biblioteca`.`libro` ;

CREATE TABLE IF NOT EXISTS `biblioteca`.`libro` (
  `id_libro` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(40) NOT NULL,
  `autor` VARCHAR(40) NOT NULL,
  `stock` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_libro`))
ENGINE = InnoDB
AUTO_INCREMENT = 24
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `biblioteca`.`prestamo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `biblioteca`.`prestamo` ;

CREATE TABLE IF NOT EXISTS `biblioteca`.`prestamo` (
  `id_prestamo` INT NOT NULL AUTO_INCREMENT,
  `usuario` INT NOT NULL,
  `libro` INT NOT NULL,
  `fecha_prestamo` DATETIME NOT NULL,
  `fecha_devolucion` DATETIME NOT NULL,
  PRIMARY KEY (`id_prestamo`),
  INDEX `fk_user` (`usuario` ASC) VISIBLE,
  INDEX `fk_libro` (`libro` ASC) VISIBLE,
  CONSTRAINT `fk_libro`
    FOREIGN KEY (`libro`)
    REFERENCES `biblioteca`.`libro` (`id_libro`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_user`
    FOREIGN KEY (`usuario`)
    REFERENCES `biblioteca`.`usuario` (`id_usuario`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
